# Generated by Django 3.0.5 on 2024-11-18 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0020_auto_20241118_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacist',
            name='user',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
